function kml=make_placemark(name,coordinates,description,icon_scale,icon_marker)
kml = make_xml("Placemark",...
               make_xml("name",name)+...
               make_xml("description",make_CDATA(description))+...
                   make_xml(["Style","IconStyle"],...
                       make_xml("scale",icon_scale)+...
                       make_xml(["Icon","href"],icon_marker))+...
                   make_xml(["Point","coordinates"],coordinates));                            
end